### ISSUE TITLE
Duplicate numbers when using pagination

### ISSUE THREAD

**Issue by htmlburger-git** [2createStudio/carbon-pagination#22]
Using the following code:
https://gist.github.com/htmlburger-git/857f89d95e4456fd89c4

results in a duplicate number issue:
https://gist.github.com/htmlburger-git/84c886872e291500d2df

Using default authors archive page without custom query or any query manipulations.

PP

**Comment by tyxla** [comment]
Thanks for reporting the issue!

It has been fixed in https://github.com/2createStudio/carbon-pagination/commit/5925f8f8eecbe49c0b7b4c95e2c581abe4659a80.

As the issue demonstrated, the page items in `Carbon_Pagination_Item_Number_Links::generate_large_number_pages_after()` were not being calculated properly. Reasons for that were:

1) The `$from` was not properly relating to `$number_limit`.
2) The `$to` was not covering some cases (the `generate_pages()` uses 0-based indexes, which means the last item was skipped in some cases.

Both of these have been addressed in https://github.com/2createStudio/carbon-pagination/commit/5925f8f8eecbe49c0b7b4c95e2c581abe4659a80.
